config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    member do
      get 'add_ingredient'
      get 'shopping_list'
    end
  end

  resources :foods
  devise_for :users
  resources :recipe_foods, only: [:create]
  
  get '/general_shopping_list', to: 'general_shopping_list#index'
  get '/public_recipes', to: 'public_recipes#index'
  root "public_recipes#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if (user.role = 'admin')
      can :manage, Food, user_id: user.id
      can :manage, Recipe, user_id: user.id
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :authorize_user, unless: :devise_controller?
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end

  def authorize_user
    return if user_signed_in? || request.path == '/'

    redirect_to new_user_session_path, alert: 'You are not authorized to access this page.'
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user! # Add this line if you want to authenticate users

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params.except(:recipe_food_quantity))
    @food.user = current_user

    respond_to do |format|
      if @food.save
        if params[:food][:recipe_id]
          RecipeFood.create(recipe: Recipe.find(params[:food][:recipe_id]), food: @food,
                            quantity: params[:food][:recipe_food_quantity])
        end
        format.html { redirect_to request.referrer, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { redirect_to request.referrer, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to request.referrer, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @recipe_foods = @food.recipe_food
    @recipe_foods.destroy_all
    @food.destroy

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :unit, :price, :quantity)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  def index
    @foods = Food.where(user: current_user)
    @recipes = Recipe.includes(:recipe_food).where(user: current_user)
    @recipe_foods = []
    @recipes.each do |recipe|
      recipe.recipe_food.each do |recipe_food|
        @recipe_foods << recipe_food
      end
    end
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  # before_action :skip_authorization, only: :index

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = Recipe.find(params[:recipe_food][:recipe_id])
    @recipe_food.food = Food.find(params[:food_id])

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_url(Recipe.first), notice: 'Ingredient was added succesfully' }
      end
    end
  end

  protected

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy add_ingredient]
  before_action :authenticate_user!

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user: current_user)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.includes(:recipe_food).find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe_foods = @recipe.recipe_food
    @recipe_foods.destroy_all
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_ingredient
    @foods = Food.all
    @new_food = Food.new
    @new_recipe_food = RecipeFood.new
  end

  def shopping_list
    @recipe_foods = @recipe.recipe_food
    @user_foods = Food.where(user: current_user)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= food.unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="container text-center py-5">
  <h1>Editing food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    <%= link_to "Show this food", @food %> |
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>

app/views/foods/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <div class="text-end my-5">
    <button class="btn_bottom_border"><%= link_to "New food", new_food_path, class: "text-decoration-none text-dark"%></button>
  </div>

  <div id="foods" class="mx-5">
    <table class="table table-striped rounded-table m-0">
      <thead>
        <tr>
          <th scope="col">
            <span>Food</span>
            <span><i class="fa fa-caret-up" aria-hidden="true"></i></span>
          </th>
          <th scope="col">Measurement unit</th>
          <th scope="col">Unit price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.quantity %></td>
            <td>$<%= food.price %></td>
            <td>
            <div class="d-flex action_delete">
              <%= link_to "Edit this food", edit_food_path(food.id) %>&nbsp;|&nbsp;
              <%= button_to "Delete", food, method: :delete, class: "border border-0 text-decoration-underline text-primary" %>
            </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container text-center py-5">
  <h1>New food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/general_shopping_list/_list.html.erb
<% total = [] %>
<table class='shopping_list_table'>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  <% elements_to_buy.each do |element| %>
    <tr>
      <td><%= element.food.name %></td>
      <td><%= element.quantity %> <%= element.food.unit %></td>
      <td>$<%= price = element.food.price * element.quantity %></td>
      <% total << price %>
    </tr>
  <% end %>
</table>
<p>
  <strong>Amount of items to buy: </strong>
  <%= total.length %>
  <strong>Total value of food needed: </strong>
   $<%= total.sum %>
</p>

app/views/general_shopping_list/index.html.erb
<section class='shopping_list_container'>
  <h1>General shopping list</h1>
  <% elements_to_buy = [] %>

  <% @recipe_foods.each do |recipe_food| %>
    <% if @foods.none? { |food| food.id == recipe_food.food.id } %>
      <% elements_to_buy << recipe_food %>
    <% else %>
      <% user_food = @foods.find { |food| food.id == recipe_food.food.id } %>
      <%if user_food.quantity < recipe_food.quantity%>
        <% element_to_buy = recipe_food.dup %>
        <% element_to_buy.quantity = recipe_food.quantity - user_food.quantity %>
        <% elements_to_buy << element_to_buy %>
      <% end %>
    <% end %>
  <% end %>

  <% if elements_to_buy.length > 0 %>
    <%= render 'list', elements_to_buy: elements_to_buy %>
  <% else %>
    <h4>You have everything you need to cook this recipe :-)</h4>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
      <%= link_to "Public Recipes", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Food", foods_path, class: "nav-link" %> <span class="nav-link">|</span>
            <%= link_to "My Recipes", recipes_path, class: "nav-link" %> <span class="nav-link">|</span>
            <%= link_to "General shopping list", general_shopping_list_path, class: "nav-link" %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/public_recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/public_recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="text-center">
    <h1>Recipes shared by the comunity</h1>
  </div>

  <div id="recipes">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe, class: "row border border-black p-2 m-3 recipes_head" do %>
        <div class="col-md-3">
          <h2><%= recipe.name %></h2>
          <% user = User.find_by(id: recipe.user_id) %>
          <p>By <%= user.name if user %></p>
        </div>
        <div class="col-md-9">
          <p><%= recipe.description %></p>
        </div>
      <% end %>
    <% end %>
  
</div>

app/views/recipes/_food_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.number_field :quantity, style: "display: none", value: 0 %>
  </div>

  <div>
    <%= form.number_field :recipe_id, style: "display: none", value: params[:id] %>
  </div>

  <div>
    <%= form.label :recipe_food_quantity, style: "display: block" %>
    <%= form.number_field :recipe_food_quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_ingredient_form.html.erb
<%= form_with(model: new_recipe_food, url: recipe_foods_path, method: :post) do |form| %>
    
    <% if new_recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(new_recipe_food.errors.count, "error") %> prohibited this recipe food from being saved:</h2>

      <ul>
        <% new_recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form.hidden_field :recipe_id, value: params[:id] %>

    <%= select_tag :food_id, options_from_collection_for_select(@foods, :id, :name), prompt: "Select the food to add" %>

    <div>
      <%= form.label :quantity, style: "display: block" %>
      <%= form.number_field :quantity %>
    </div>
    
    <div>
      <%= form.submit "Add ingredient" %>
    </div>
  <% end %>

app/views/recipes/_ingredients_list.html.erb
<table>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Value</th>
    <th>Actions</th>
  </tr>
  <% @recipe.recipe_food.each do |recipe_food| %>
    <tr>
      <td><%= recipe_food.food.name %></td>
      <td><%= recipe_food.quantity %></td>
      <td><%= recipe_food.food.price %></td>
      <td>
        <%= button_to "Destroy", recipe_food.food, method: :delete, class: 'table_button' %>,
        <%= link_to "Edit", edit_food_path(recipe_food.food) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/recipes/_recipe.html.erb
<h2 id='recipe_show_title'>
  <%= recipe.name.capitalize %>
</h2>

<p>
  <strong>Preparation time:</strong>
  <%= recipe.preparation_time %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= recipe.cooking_time %>
</p>

<p>
  <strong>Steps:</strong>
  <%= recipe.description %>
</p>

app/views/recipes/add_ingredient.html.erb
<p style="color: green"><%= notice %></p>
<h1>New ingredient</h1>

<div class="add_ingredient_container">
  <div>
    <p>Choose one food</p>
    <%= render "ingredient_form", new_recipe_food: @new_recipe_food %>  
  </div>

  <h5> or/ </h5>

  <div>
    <p>Add a new food</p>
    <%= render "food_form", food: @new_food %>
    
  </div>
</div>

<div>
  <%= link_to "Back to the recipe", recipe_path(params[:id]) %>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="text-end my-5">
    <button class="btn_bottom_border"><%= link_to "New recipe", new_recipe_path, class: "text-decoration-none text-dark" %></button>
</div>

<div class="container">
  <h1>Recipes</h1>

  <div id="recipes">
    <% @recipes.each do |recipe| %>
      <div class="row border border-black p-2 m-3 recipes_head">
        <div class="col-md-3">
          <h2><%= recipe.name %></h2>
          <%= button_to "Remove", recipe, method: :delete, class: %>
        </div>
        <div class="col-md-9">
          <p><%= recipe.description %></p>
        </div>
      </div>
      <%= link_to "Show this recipe", recipe, class: "my-class" %>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container text-center py-5">
  <h1>New recipe</h1>

  <%= render "form", recipe: @recipe %>

  <br>

  <div>
    <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>

app/views/recipes/shopping_list.html.erb
<h1><%= @recipe.name.capitalize %> shopping list</h1>

<% elements_to_buy = [] %>

<% @recipe_foods.each do |recipe_food| %>
  <% if @user_foods.none? { |food| food.id == recipe_food.food.id } %>
    <% elements_to_buy << recipe_food %>
  <% else %>
    <% user_food = @user_foods.find { |food| food.id == recipe_food.food.id } %>
    <%if user_food.quantity < recipe_food.quantity%>
      <% element_to_buy = recipe_food.dup %>
      <% element_to_buy.quantity = recipe_food.quantity - user_food.quantity %>
      <% elements_to_buy << element_to_buy %>
    <% end %>
  <% end %>
<% end %>

<% if elements_to_buy.length > 0 %>
  <ul>
    <% elements_to_buy.each do |elements_to_buy| %>
      <li><%= elements_to_buy.food.name %>: <%= elements_to_buy.quantity %> <%= elements_to_buy.food.unit %></li>
    <% end %>
  </ul>
<% else %>
  <h4>You have everything you need to cook this recipe :-)</h4>
<% end %>

<%= link_to "Back to the recipe", recipe_path(params[:id]) %>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class='recipe_container'>
  <%= form_with(model: @recipe, url: "/recipes/#{@recipe.id}", method: :patch, class: 'form_to_public_toggle') do |form| %>
    <%= form.check_box :public, checked: !@recipe.public?, class: 'no_visible'%>

    <% if @recipe.public %>
    <% button_message = 'Make recipe private' %>
    <% button_class = 'make-recipe-private' %>
    <% else %>
    <% button_message = 'Make recipe public' %>
    <% button_class = 'make-recipe-public' %>
    <% end %>

    <%= form.submit "#{button_message}", class: "#{button_class}" %>
  <% end %>

  <%= render @recipe %>
  <div class='recipe_show_links'>
    <%= link_to "Add an ingredient", add_ingredient_recipe_path(@recipe) %> |
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
    <%= link_to "Back to recipes", recipes_path %>
  </div>

  <%= link_to "Generate shopping list", shopping_list_recipe_path(@recipe) %>
  <%= render 'ingredients_list' %>

</div>

<div>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>